### ISSUE TITLE
Error with unsafe build flags

### ISSUE THREAD

**Issue by chidiwilliams** [ggerganov/whisper.spm#4]
I'm not sure what I'm doing wrong, but I keep running into this error with the unsafe flags in the build:

> The package product 'whisper' cannot be used as a dependency of this target because it uses unsafe build flags.

Does any one know how I can work around this? I have tried importing the package using the commit hash and branch, but still no luck.

Xcode version 14

**Comment by finnvoor** [comment]
That error only happens when importing using a tag. Importing by branch or commit hash both work fine, if you are still getting the error I would suggest resolving package dependencies / clear packages / close and reopen Xcode.

**Comment by chidiwilliams** [comment]
You're correct, thanks. Clearing packages and restarting Xcode didn't work, but creating a new project did.

**Comment by bdrelling** [comment]
I'm getting this issue as well:

```
xcodebuild: error: Could not resolve package dependencies:
  the target 'whisper' in product 'whisper' contains unsafe build flags
```

It's directly related to the resolution around PR #1 in this repo.

@ggerganov Given that tags won't work for this repo, I think we may need to find another solution? For now, we'll pin to the commit.

**Comment by Kshitij876** [comment]
<img width="1142" alt="Screenshot 2024-06-04 at 12 02 00 PM" src="https://github.com/ggerganov/whisper.spm/assets/135306641/623749e6-a464-4abc-9192-69d8cda134b3">

Getting this same error even after setting the dependency to branch -> master . Tried the resolving package dependencies / clear packages / close and reopen Xcode as well. still getting the "The package product 'whisper' cannot be used as a dependency of this target because it uses unsafe build flags.
" error when installing the whisper package
